// A compact public-domain short-word list for passphrases. Based on common
// short English nouns/verbs/adjectives (CC0-equivalent). Designed for
// memorable Diceware-style passphrases; ~360 entries → ~8.5 bits/word.
//
// For maximum entropy use 6+ words.
export const SHORT_WORDS: readonly string[] = [
  'able', 'acid', 'aged', 'aide', 'aims', 'airs', 'alps', 'amid', 'ammo', 'amok',
  'apex', 'apse', 'arch', 'arms', 'arts', 'atom', 'auto', 'aware', 'baby', 'back',
  'bail', 'bait', 'bake', 'bald', 'ball', 'balm', 'band', 'bang', 'bank', 'bard',
  'bark', 'barn', 'base', 'bash', 'bask', 'bath', 'baton', 'bay', 'beach', 'bead',
  'beak', 'bean', 'bear', 'beat', 'beef', 'beep', 'beer', 'bell', 'belt', 'bench',
  'bend', 'bent', 'best', 'bias', 'bide', 'bike', 'bill', 'bind', 'bird', 'bite',
  'blade', 'blame', 'blank', 'blast', 'blaze', 'bleed', 'bless', 'blew', 'blind',
  'blink', 'block', 'blond', 'blood', 'blow', 'blue', 'blur', 'blush', 'board',
  'boast', 'boat', 'body', 'boil', 'bold', 'bolt', 'bomb', 'bond', 'bone', 'book',
  'boom', 'boon', 'boot', 'born', 'boss', 'both', 'bowl', 'box', 'brace', 'brag',
  'brain', 'brake', 'brand', 'brave', 'bread', 'break', 'brick', 'bride', 'brief',
  'bring', 'brisk', 'broad', 'broke', 'brook', 'broom', 'brown', 'brunch', 'brush',
  'buck', 'budge', 'buff', 'bug', 'bulb', 'bulk', 'bull', 'bump', 'bunch', 'bunk',
  'burn', 'burr', 'burst', 'bury', 'bus', 'bush', 'busy', 'butter', 'buzz', 'cab',
  'cabin', 'cable', 'cache', 'cage', 'cake', 'calf', 'call', 'calm', 'came', 'camp',
  'can', 'cape', 'card', 'care', 'cargo', 'carry', 'cart', 'case', 'cash', 'cast',
  'cat', 'catch', 'cave', 'cedar', 'cell', 'cent', 'chain', 'chair', 'chalk',
  'chant', 'chap', 'charm', 'chart', 'chase', 'cheap', 'cheek', 'cheer', 'chef',
  'chess', 'chest', 'chew', 'chick', 'chief', 'child', 'chill', 'chime', 'chin',
  'chip', 'chirp', 'chop', 'chose', 'chuck', 'chunk', 'churn', 'cigar', 'clad',
  'claim', 'clamp', 'clan', 'clap', 'clash', 'clasp', 'class', 'claw', 'clay',
  'clean', 'clear', 'cleat', 'clerk', 'click', 'cliff', 'climb', 'cling', 'clip',
  'clock', 'clog', 'clone', 'close', 'cloth', 'cloud', 'clout', 'clove', 'clown',
  'club', 'clue', 'coach', 'coal', 'coast', 'coat', 'cobra', 'cod', 'code', 'coil',
  'coin', 'cold', 'comb', 'come', 'cone', 'cook', 'cool', 'cope', 'copy', 'cord',
  'core', 'cork', 'corn', 'cost', 'couch', 'cough', 'count', 'court', 'cover',
  'cow', 'crab', 'crack', 'craft', 'crag', 'cram', 'crane', 'crank', 'crash',
  'crate', 'crave', 'crawl', 'craze', 'crazy', 'cream', 'creek', 'creep', 'crepe',
  'crew', 'crib', 'crime', 'crimp', 'crisp', 'croak', 'crock', 'crook', 'crop',
  'cross', 'crow', 'crowd', 'crown', 'crumb', 'crush', 'crust', 'cry', 'cub',
  'cube', 'cuff', 'cult', 'curb', 'cure', 'curl', 'curse', 'curve', 'cusp', 'cut',
  'cute', 'dab', 'dad', 'daily', 'dairy', 'daisy', 'dale', 'dam', 'dame', 'damp',
  'dance', 'dare', 'dark', 'dash', 'date', 'dawn', 'day', 'daze', 'dead', 'deaf',
  'deal', 'dean', 'dear', 'debt', 'decaf', 'deck', 'decoy', 'deed', 'deep', 'deer',
  'delay', 'dell', 'delta', 'demo', 'den', 'dent', 'depot', 'derby', 'desk', 'dial',
  'diary', 'dice', 'dig', 'dim', 'dime', 'dine', 'ding', 'dingo', 'dirt', 'dirty',
  'disc', 'dish', 'disk', 'dive', 'dizzy', 'dock', 'doe', 'dog', 'doll', 'dome',
  'done', 'donor', 'door', 'dose', 'dot', 'dough', 'dove', 'down', 'doze', 'dozen',
  'draft', 'drag', 'drain', 'drama', 'drank', 'draw', 'dream', 'dress', 'drew',
  'dried', 'drift', 'drill', 'drink', 'drip', 'drive', 'drone', 'drool', 'droop',
  'drop', 'drove', 'drown', 'drug', 'drum', 'dry', 'duck', 'duct', 'due', 'duel',
  'duet', 'duke', 'dull', 'duly', 'dumb', 'dune', 'dunk', 'duo', 'dusk', 'dust',
  'duty', 'dwarf', 'dye', 'eager', 'eagle', 'ear', 'early', 'earn', 'earth', 'east',
  'easy', 'eat', 'echo', 'edge', 'edit', 'eel', 'eerie', 'egg', 'eight', 'elbow',
  'elder', 'elf', 'elite', 'elk', 'elm', 'elope', 'else', 'elude', 'elves', 'email',
  'ember', 'empty', 'end', 'endow', 'enemy', 'enjoy', 'enter', 'entry', 'envoy',
  'equal', 'equip', 'erase', 'error', 'erupt', 'essay', 'evade', 'even', 'event',
  'every', 'evict', 'evil', 'exact', 'exam', 'excel', 'exit', 'expel', 'extra',
  'eye', 'fable', 'face', 'fact', 'fade', 'fail', 'faint', 'fair', 'fall', 'false',
  'fame', 'fan', 'fang', 'far', 'farm', 'fast', 'fat', 'fate', 'fault', 'fawn',
  'fax', 'fear', 'feast', 'feat', 'fed', 'fee', 'feed', 'feel', 'fell', 'felt',
  'fence', 'fern', 'ferry', 'fest', 'fetch', 'fetus', 'feud', 'fever', 'few',
  'fiber', 'field', 'fiend', 'fierce', 'fifth', 'fifty', 'fig', 'fight', 'figure',
  'file', 'fill', 'film', 'final', 'find', 'fine', 'finger', 'finish', 'fire',
  'firm', 'first', 'fish', 'fist', 'fit', 'five', 'fix', 'fizz', 'flag', 'flake',
  'flame', 'flap', 'flare', 'flash', 'flat', 'flaw', 'flax', 'flea', 'fleck',
  'fled', 'flee', 'fleet', 'flesh', 'flew', 'flex', 'flick', 'flier', 'flight',
  'fling', 'flint', 'flip', 'flirt', 'float', 'flock', 'flood', 'floor', 'flop',
  'floss', 'flour', 'flow', 'flue', 'fluff', 'fluid', 'flunk', 'flush', 'flute',
  'fly', 'foam', 'focus', 'foe', 'fog', 'foil', 'fold', 'folk', 'fond', 'font',
  'food', 'fool', 'foot', 'force', 'fork', 'form', 'fort', 'forth', 'forty',
  'forum', 'fossil', 'foster', 'foul', 'found', 'four', 'fowl', 'fox', 'frail',
  'frame', 'frank', 'fraud', 'free', 'fresh', 'fret', 'friar', 'fried', 'fries',
  'frill', 'frisk', 'frog', 'from', 'front', 'frost', 'froth', 'frown', 'froze',
  'fruit', 'fudge', 'fuel', 'full', 'fume', 'fun', 'fund', 'funk', 'funny',
  'furry', 'fury', 'fuse', 'fussy', 'gadget', 'gain', 'gala', 'gale', 'gallop',
  'game', 'gamma', 'gang', 'gap', 'garlic', 'gas', 'gash', 'gasp', 'gate', 'gather',
  'gauge', 'gauze', 'gave', 'gawk', 'gaze', 'gear', 'gecko', 'gel', 'gem', 'gene',
  'genie', 'genre', 'gent', 'get', 'geyser', 'ghost', 'giant', 'gift', 'giggle',
  'gild', 'gill', 'gilt', 'gimp', 'ginger', 'girl', 'give', 'glad', 'glance',
  'glare', 'glass', 'glaze', 'gleam', 'glean', 'glide', 'glint', 'globe', 'gloom',
  'glory', 'gloss', 'glove', 'glow', 'glue', 'gnarl', 'gnat', 'gnaw', 'goal',
  'goat', 'gobble', 'gold', 'golf', 'gone', 'good', 'goofy', 'goose', 'gore',
  'gosh', 'gourd', 'gown', 'grab', 'grace', 'grade', 'grain', 'gram', 'grand',
  'grape', 'graph', 'grasp', 'grass', 'grate', 'grave', 'gravy', 'gray', 'great',
  'greed', 'green', 'greet', 'grew', 'grid', 'grief', 'grill', 'grim', 'grin',
  'grip', 'grit', 'groan', 'groin', 'groom', 'grope', 'gross', 'group', 'grout',
  'grove', 'grow', 'grub', 'gruel', 'gruff', 'grunt', 'guard', 'guess', 'guest',
  'guide', 'guild', 'guilt', 'gulf', 'gull', 'gulp', 'gum', 'gun', 'guru', 'gush',
  'gust', 'gut', 'guy', 'gym', 'gypsy', 'habit', 'hack', 'haggle', 'hail', 'hair',
  'half', 'hall', 'halo', 'halt', 'ham', 'hand', 'hang', 'happy', 'harbor', 'hard',
  'hare', 'hark', 'harm', 'harp', 'harsh', 'harvest', 'has', 'hash', 'hat', 'hatch',
  'hate', 'haul', 'haunt', 'have', 'haven', 'hawk', 'hay', 'hazel', 'hazy',
  'head', 'heap', 'hear', 'heart', 'heat', 'heave', 'heavy', 'heel', 'hefty',
  'helix', 'hello', 'helm', 'help', 'hem', 'hen', 'hence', 'herb', 'herd', 'here',
  'hero', 'hex', 'hey', 'hi', 'hick', 'hide', 'high', 'hill', 'hilt', 'hint',
  'hip', 'hire', 'his', 'hiss', 'hit', 'hive', 'hoard', 'hoarse', 'hobby', 'hockey',
  'hog', 'hoist', 'hold', 'hole', 'hollow', 'holy', 'home', 'honey', 'honk', 'honor',
  'hood', 'hoof', 'hook', 'hoop', 'hop', 'hope', 'horn', 'horse', 'hose', 'hospital',
  'host', 'hot', 'hotel', 'hound', 'hour', 'house', 'hover', 'how', 'howl', 'huddle',
  'hue', 'huff', 'hug', 'huge', 'hull', 'hum', 'human', 'humid', 'hump', 'hunch',
  'hung', 'hunk', 'hunt', 'hurdle', 'hurl', 'hurt', 'hush', 'hutch', 'hyena', 'ice',
  'icing', 'icon', 'idea', 'idle', 'idol', 'iffy', 'igloo', 'ill', 'image', 'imp',
  'imply', 'impose', 'inch', 'index', 'indoor', 'infant', 'ingot', 'inhale',
  'inject', 'inland', 'inn', 'inner', 'input', 'iris', 'iron', 'irony', 'islam',
  'island', 'isle', 'issue', 'item', 'itself', 'ivory', 'jab', 'jackal', 'jacket',
  'jade', 'jagged', 'jaguar', 'jail', 'jam', 'jar', 'jaunt', 'jaw', 'jay', 'jazz',
  'jealous', 'jeer', 'jelly', 'jerk', 'jersey', 'jest', 'jet', 'jewel', 'jig',
  'jiggle', 'jingle', 'job', 'jockey', 'jog', 'join', 'joint', 'joke', 'jolly',
  'jolt', 'jot', 'journey', 'joust', 'joy', 'judge', 'judo', 'jug', 'juice',
  'juicy', 'July', 'jumbo', 'jump', 'jungle', 'junior', 'junk', 'jury', 'just',
  'kale', 'karate', 'keep', 'keg', 'kelp', 'kept', 'ketchup', 'kettle', 'key',
  'kick', 'kid', 'kidney', 'kill', 'kilt', 'kin', 'kind', 'king', 'kink', 'kiss',
  'kit', 'kite', 'kitten', 'kiwi', 'knack', 'knead', 'knee', 'kneel', 'knew',
  'knife', 'knight', 'knit', 'knob', 'knock', 'knot', 'know', 'koala', 'kraut',
  'lab', 'label', 'labor', 'lace', 'lack', 'ladle', 'lady', 'lag', 'lair', 'lake',
  'lamb', 'lame', 'lamp', 'land', 'lane', 'lap', 'large', 'larva', 'laser',
  'lasso', 'last', 'latch', 'late', 'lather', 'latter', 'laugh', 'launch', 'lava',
  'law', 'lawn', 'lay', 'lazy', 'leach', 'lead', 'leaf', 'leak', 'lean', 'leap',
  'learn', 'lease', 'leash', 'least', 'leave', 'ledge', 'leek', 'left', 'leg',
  'legal', 'lemon', 'lend', 'length', 'lens', 'lent', 'leopard', 'less', 'lesson',
  'let', 'level', 'lever', 'liable', 'liar', 'lick', 'lid', 'lie', 'lift', 'light',
  'like', 'lilac', 'lily', 'limb', 'lime', 'limit', 'limp', 'line', 'linen',
  'linger', 'link', 'lint', 'lion', 'lip', 'list', 'lit', 'liter', 'live', 'lizard',
  'load', 'loaf', 'loan', 'lobby', 'lobe', 'local', 'lock', 'lodge', 'loft',
  'log', 'logic', 'logo', 'loiter', 'lone', 'long', 'look', 'loom', 'loop', 'loose',
  'loot', 'lord', 'lose', 'loss', 'lost', 'lot', 'lotion', 'lotus', 'loud',
  'lounge', 'lousy', 'love', 'low', 'lower', 'loyal', 'luck', 'lull', 'lumber',
  'lump', 'lunar', 'lunch', 'lung', 'lurch', 'lure', 'lurk', 'lush', 'lying',
  'lyric', 'macaw', 'macro', 'mad', 'madam', 'magic', 'maid', 'mail', 'main',
  'major', 'make', 'male', 'mall', 'malt', 'mama', 'mango', 'manor', 'mantle',
  'many', 'map', 'maple', 'march', 'mare', 'mark', 'marsh', 'mart', 'mask',
  'mass', 'mast', 'match', 'mate', 'math', 'matrix', 'matter', 'maxim', 'maybe',
  'mayor', 'maze', 'meadow', 'meal', 'mean', 'meant', 'meat', 'medal', 'media',
  'medic', 'melon', 'melt', 'memo', 'mend', 'mental', 'mercy', 'merge', 'merit',
  'merry', 'mesh', 'mess', 'metal', 'meter', 'mid', 'might', 'mild', 'mile',
  'milk', 'mill', 'mimic', 'mind', 'mine', 'mingle', 'mini', 'mink', 'mint',
  'minus', 'mirror', 'miser', 'miss', 'mist', 'mix', 'moat', 'mob', 'mock',
  'modal', 'mode', 'model', 'modem', 'mogul', 'moist', 'mold', 'mole', 'molt',
  'mom', 'money', 'monk', 'mood', 'moon', 'moose', 'moral', 'more', 'morsel',
  'most', 'motel', 'moth', 'motion', 'motor', 'motto', 'mount', 'mourn', 'mouse',
  'mouth', 'movie', 'mower', 'much', 'mucus', 'mud', 'muffin', 'mug', 'mule',
  'mum', 'munch', 'mural', 'muse', 'mush', 'music', 'must', 'mute', 'mutter',
  'mutual', 'myth', 'nag', 'nail', 'name', 'nanny', 'nap', 'napkin', 'narrow',
  'nasty', 'natural', 'naval', 'navy', 'near', 'neat', 'neck', 'need', 'needle',
  'neon', 'nephew', 'nerve', 'nest', 'net', 'never', 'new', 'newt', 'next', 'nibble',
  'nice', 'niche', 'nick', 'niece', 'night', 'nimble', 'nine', 'ninth', 'nip',
  'nipple', 'noble', 'nobody', 'nod', 'noise', 'nomad', 'none', 'noon', 'noose',
  'norm', 'north', 'nose', 'nostril', 'not', 'notch', 'note', 'noun', 'nova',
  'novel', 'now', 'nozzle', 'nudge', 'null', 'numb', 'nurse', 'nut', 'nylon',
  'oak', 'oar', 'oasis', 'oat', 'oath', 'obese', 'obey', 'oboe', 'ocean', 'octane',
  'odd', 'odds', 'ode', 'odor', 'off', 'office', 'often', 'ogre', 'oil', 'okay',
  'old', 'olive', 'omega', 'omen', 'omit', 'once', 'one', 'onion', 'online',
  'only', 'onset', 'onto', 'onyx', 'opal', 'open', 'opera', 'opine', 'oppose',
  'opt', 'optic', 'oracle', 'oral', 'orange', 'orbit', 'orca', 'order', 'organ',
  'origin', 'other', 'otter', 'ought', 'ounce', 'out', 'outer', 'oval', 'oven',
  'over', 'owl', 'own', 'owner', 'oxen', 'oxide', 'pace', 'pack', 'pad', 'page',
  'paid', 'pail', 'pain', 'paint', 'pair', 'pale', 'palm', 'panel', 'panic',
  'panther', 'paper', 'parade', 'pardon', 'parent', 'park', 'parrot', 'part',
  'party', 'pass', 'past', 'pasta', 'paste', 'patch', 'path', 'patio', 'patrol',
  'pause', 'pave', 'paw', 'pay', 'peace', 'peach', 'peak', 'pear', 'pearl',
  'pebble', 'pedal', 'peek', 'peel', 'peep', 'peer', 'pelt', 'pen', 'pencil',
  'penny', 'people', 'pep', 'perch', 'period', 'perky', 'pet', 'phase', 'phone',
  'photo', 'piano', 'pick', 'picnic', 'pie', 'piece', 'pier', 'pig', 'pike', 'pile',
  'pill', 'pilot', 'pin', 'pinch', 'pine', 'pint', 'pioneer', 'pipe', 'pirate',
  'pit', 'pitch', 'pity', 'pivot', 'pixel', 'pizza', 'place', 'plaid', 'plain',
  'plan', 'plank', 'plant', 'plate', 'play', 'plaza', 'plea', 'plead', 'pledge',
  'plot', 'plow', 'pluck', 'plug', 'plum', 'plump', 'plunge', 'plus', 'pocket',
  'poem', 'poet', 'point', 'poke', 'polar', 'pole', 'polish', 'polo', 'pond',
  'pony', 'pool', 'poor', 'pop', 'popular', 'porch', 'pork', 'port', 'pose',
  'posh', 'post', 'pot', 'potato', 'pouch', 'pound', 'pour', 'power', 'praise',
  'prank', 'prawn', 'pray', 'prefer', 'press', 'pretty', 'price', 'pride', 'prince',
  'print', 'prior', 'prism', 'prize', 'probe', 'prom', 'prone', 'prong', 'proof',
  'prop', 'prose', 'proud', 'prove', 'prowl', 'prune', 'pry', 'public', 'pudding',
  'puddle', 'puff', 'pulp', 'pulse', 'pump', 'punch', 'puppy', 'purr', 'purse',
  'push', 'puzzle', 'pyre', 'quack', 'quail', 'quake', 'quarry', 'quart', 'quartz',
  'queen', 'quest', 'quick', 'quiet', 'quill', 'quilt', 'quirk', 'quirky', 'quit',
  'quiz', 'quote', 'rabbit', 'race', 'rack', 'radar', 'radio', 'raft', 'rage',
  'raid', 'rail', 'rain', 'raise', 'rake', 'rally', 'ramble', 'ramp', 'ranch',
  'random', 'range', 'rank', 'rant', 'rare', 'rash', 'rate', 'rather', 'rattle',
  'raven', 'ravine', 'razor', 'reach', 'react', 'read', 'real', 'realm', 'rear',
  'reason', 'rebel', 'recall', 'recap', 'recipe', 'record', 'recycle', 'red',
  'reef', 'refer', 'refine', 'refund', 'regal', 'region', 'relax', 'relay',
  'relic', 'rely', 'remedy', 'rent', 'repair', 'repel', 'replay', 'reply', 'report',
  'reptile', 'resort', 'rest', 'retail', 'return', 'reveal', 'review', 'rib',
  'rice', 'rich', 'rid', 'riddle', 'ride', 'ridge', 'rifle', 'rig', 'right',
  'rigid', 'rim', 'ring', 'rinse', 'riot', 'rip', 'ripe', 'risk', 'rite', 'rival',
  'river', 'road', 'roam', 'roar', 'roast', 'robe', 'robin', 'robot', 'rock',
  'rocky', 'rod', 'rode', 'rogue', 'role', 'roll', 'roof', 'room', 'roomy', 'root',
  'rope', 'rose', 'rosy', 'rot', 'rotate', 'rough', 'round', 'route', 'rove',
  'row', 'royal', 'rub', 'ruby', 'rude', 'rug', 'ruin', 'rule', 'rumor', 'run',
  'rung', 'rural', 'rush', 'rust', 'rye', 'sack', 'sad', 'saddle', 'safari',
  'safe', 'sage', 'said', 'sail', 'sake', 'salad', 'salmon', 'salon', 'salsa',
  'salt', 'salute', 'same', 'sample', 'sand', 'sang', 'sank', 'sap', 'sash',
  'satin', 'sauce', 'saucer', 'sauna', 'save', 'savor', 'savvy', 'saw', 'say',
  'scale', 'scalp', 'scam', 'scan', 'scant', 'scar', 'scarf', 'scary', 'scene',
  'scent', 'scoff', 'scold', 'scoop', 'scoot', 'scope', 'score', 'scorn', 'scout',
  'scowl', 'scrap', 'scream', 'screw', 'script', 'scroll', 'scrub', 'scruff',
  'scuff', 'sculpt', 'sea', 'seal', 'seam', 'seance', 'search', 'season', 'seat',
  'secret', 'sect', 'sedan', 'seed', 'seek', 'seem', 'seep', 'seer', 'self',
  'sell', 'send', 'senior', 'sense', 'sent', 'serene', 'serge', 'series', 'serve',
  'set', 'setup', 'seven', 'sever', 'sew', 'shack', 'shade', 'shaft', 'shake',
  'shaky', 'shall', 'sham', 'shame', 'shape', 'share', 'shark', 'sharp', 'shave',
  'shawl', 'shed', 'sheen', 'sheep', 'sheer', 'sheet', 'shelf', 'shell', 'shield',
  'shift', 'shin', 'shine', 'ship', 'shirt', 'shiver', 'shock', 'shoe', 'shone',
  'shoot', 'shop', 'shore', 'short', 'shot', 'shout', 'shove', 'show', 'shown',
  'shred', 'shrill', 'shrimp', 'shrine', 'shrink', 'shrub', 'shrug', 'shun',
  'shut', 'shy', 'sick', 'side', 'sift', 'sigh', 'sight', 'sign', 'silk', 'sill',
  'silly', 'silo', 'silver', 'simple', 'sin', 'since', 'sing', 'sink', 'sip',
  'siren', 'sis', 'sister', 'sit', 'site', 'six', 'sixth', 'size', 'sketch',
  'ski', 'skid', 'skiff', 'skill', 'skim', 'skin', 'skip', 'skirt', 'skit', 'skull',
  'sky', 'slab', 'slack', 'slain', 'slam', 'slang', 'slap', 'slash', 'slat',
  'slate', 'slave', 'sleek', 'sleep', 'sleet', 'sleeve', 'slept', 'slice', 'slid',
  'slide', 'slim', 'slime', 'sling', 'slip', 'slit', 'slither', 'sliver', 'slogan',
  'slope', 'slot', 'sloth', 'slow', 'slug', 'slum', 'slump', 'slung', 'slur',
  'slush', 'sly', 'small', 'smart', 'smash', 'smear', 'smell', 'smelt', 'smile',
  'smirk', 'smith', 'smog', 'smoke', 'smug', 'snack', 'snag', 'snail', 'snake',
  'snap', 'snare', 'snarl', 'sneak', 'sneer', 'sniff', 'snip', 'snob', 'snoop',
  'snore', 'snort', 'snot', 'snow', 'snug', 'soak', 'soap', 'soar', 'sob', 'soda',
  'sofa', 'soft', 'soggy', 'soil', 'solar', 'sold', 'solid', 'solo', 'solve',
  'some', 'son', 'song', 'soon', 'sore', 'sorry', 'sort', 'soul', 'soup', 'sour',
  'south', 'sow', 'soy', 'space', 'spade', 'span', 'spank', 'spare', 'spark',
  'spasm', 'spat', 'spawn', 'speak', 'spear', 'speech', 'speed', 'spell', 'spend',
  'spent', 'spew', 'spice', 'spider', 'spied', 'spike', 'spill', 'spin', 'spine',
  'spire', 'spit', 'spite', 'splat', 'splay', 'split', 'spoil', 'spoke', 'sponge',
  'spool', 'spoon', 'sport', 'spot', 'spout', 'sprain', 'spray', 'spread', 'spring',
  'spry', 'spun', 'spur', 'spurt', 'spy', 'squad', 'squat', 'squid', 'stab',
  'stack', 'staff', 'stage', 'staid', 'stain', 'stair', 'stake', 'stale', 'stall',
  'stamp', 'stand', 'stank', 'staple', 'star', 'stare', 'start', 'state', 'stay',
  'stead', 'steady', 'steak', 'steal', 'steam', 'steel', 'steep', 'steer', 'stem',
  'step', 'stew', 'stick', 'sticky', 'stiff', 'still', 'sting', 'stink', 'stir',
  'stitch', 'stock', 'stoic', 'stoke', 'stole', 'stomp', 'stone', 'stood', 'stool',
  'stoop', 'stop', 'store', 'stork', 'storm', 'story', 'stout', 'stove', 'straw',
  'strap', 'stray', 'strut', 'stub', 'stuck', 'stud', 'study', 'stuff', 'stump',
  'stung', 'stunt', 'sturdy', 'style', 'sub', 'suburb', 'such', 'suck', 'sudden',
  'suds', 'sugar', 'suit', 'sulk', 'sum', 'sun', 'sunny', 'super', 'sure', 'surf',
  'surge', 'sushi', 'swab', 'swag', 'swam', 'swan', 'swap', 'swarm', 'swat',
  'swatch', 'sway', 'swear', 'sweat', 'sweep', 'sweet', 'swell', 'swept', 'swift',
  'swig', 'swim', 'swine', 'swing', 'swipe', 'swirl', 'swish', 'switch', 'sword',
  'swore', 'sworn', 'swum', 'swung', 'syrup', 'system', 'tab', 'table', 'taco',
  'tact', 'tag', 'tail', 'take', 'tale', 'talk', 'tall', 'tame', 'tan', 'tang',
  'tank', 'tap', 'tape', 'taper', 'taps', 'tar', 'tart', 'task', 'taste', 'taut',
  'tax', 'taxi', 'tea', 'teach', 'team', 'tear', 'tease', 'tech', 'teem', 'teen',
  'teeth', 'tell', 'temper', 'temple', 'ten', 'tenant', 'tend', 'tense', 'tent',
  'term', 'tern', 'test', 'text', 'thank', 'thaw', 'theft', 'their', 'them',
  'theme', 'then', 'there', 'they', 'thick', 'thief', 'thigh', 'thin', 'thing',
  'think', 'third', 'this', 'thong', 'thorn', 'those', 'though', 'thread', 'three',
  'threw', 'thrill', 'throb', 'throw', 'thrust', 'thud', 'thumb', 'thump', 'thus',
  'tick', 'tidal', 'tide', 'tidy', 'tie', 'tiger', 'tight', 'tile', 'tilt', 'time',
  'tin', 'tinge', 'tint', 'tiny', 'tip', 'tire', 'title', 'toad', 'toast', 'today',
  'toe', 'tofu', 'toil', 'token', 'told', 'toll', 'tomb', 'tone', 'tongs', 'tonic',
  'too', 'took', 'tool', 'tooth', 'top', 'topic', 'torch', 'tore', 'torso',
  'toss', 'total', 'touch', 'tough', 'tour', 'tout', 'tow', 'towel', 'tower',
  'town', 'toxic', 'toy', 'trace', 'track', 'trade', 'trail', 'train', 'trait',
  'tramp', 'trance', 'trap', 'trash', 'tray', 'tread', 'treat', 'tree', 'trek',
  'tremor', 'trench', 'trend', 'tribe', 'trick', 'tried', 'trio', 'trip', 'trolley',
  'troop', 'trot', 'truce', 'truck', 'true', 'truly', 'trump', 'trunk', 'trust',
  'truth', 'try', 'tub', 'tuba', 'tube', 'tuck', 'tuft', 'tug', 'tulip', 'tumble',
  'tuna', 'tune', 'tunic', 'turf', 'turn', 'tusk', 'tutor', 'twig', 'twin',
  'twine', 'twirl', 'twist', 'two', 'tying', 'type', 'ugly', 'unable', 'uncle',
  'under', 'undo', 'unfair', 'unfit', 'unify', 'union', 'unique', 'unit', 'unkind',
  'unless', 'unload', 'unlock', 'until', 'unwrap', 'upbeat', 'upend', 'upkeep',
  'upon', 'upper', 'upset', 'urban', 'urge', 'usable', 'usage', 'usher', 'usual',
  'utter', 'vacate', 'vague', 'vain', 'valet', 'valid', 'value', 'valve', 'van',
  'vane', 'vapor', 'vary', 'vase', 'vast', 'vat', 'vault', 'veal', 'veer',
  'veggie', 'veil', 'vein', 'velvet', 'vendor', 'venom', 'vent', 'venue', 'verb',
  'verge', 'verse', 'very', 'vessel', 'vest', 'vetch', 'veto', 'vex', 'via',
  'vice', 'video', 'view', 'vigil', 'villa', 'vine', 'viola', 'violet', 'viper',
  'viral', 'virus', 'visa', 'visit', 'visor', 'vista', 'vivid', 'vixen', 'vocal',
  'vogue', 'voice', 'void', 'volley', 'volt', 'vote', 'voter', 'voucher', 'vow',
  'vowel', 'voyage', 'wad', 'wade', 'wafer', 'wag', 'wage', 'wagon', 'wail',
  'waist', 'wait', 'waiter', 'wake', 'walk', 'wall', 'wallet', 'walrus', 'wand',
  'wander', 'wane', 'want', 'war', 'ward', 'ware', 'warm', 'warn', 'warp', 'wart',
  'wary', 'wash', 'wasp', 'waste', 'watch', 'water', 'watt', 'wave', 'wax', 'way',
  'weak', 'wealth', 'wean', 'wear', 'weary', 'weave', 'web', 'wed', 'wedge',
  'weed', 'week', 'weep', 'weigh', 'weird', 'well', 'went', 'were', 'west', 'wet',
  'whack', 'whale', 'wharf', 'what', 'wheat', 'wheel', 'when', 'where', 'whew',
  'whiff', 'which', 'while', 'whim', 'whine', 'whip', 'whirl', 'whisk', 'white',
  'whole', 'whom', 'whose', 'why', 'wick', 'wide', 'widow', 'width', 'wield',
  'wife', 'wig', 'wiggle', 'wild', 'will', 'willow', 'wilt', 'wily', 'win',
  'wince', 'winch', 'wind', 'wine', 'wing', 'wink', 'winner', 'wipe', 'wire',
  'wise', 'wish', 'wisp', 'wit', 'witch', 'with', 'witty', 'wizard', 'wobble',
  'woe', 'woke', 'wolf', 'woman', 'won', 'wonder', 'wood', 'wool', 'word', 'wore',
  'work', 'world', 'worm', 'worn', 'worry', 'worse', 'worst', 'worth', 'wound',
  'woven', 'wow', 'wrap', 'wrath', 'wreck', 'wrench', 'wrest', 'wring', 'wrist',
  'write', 'wrong', 'wrote', 'wrung', 'yacht', 'yak', 'yam', 'yank', 'yard',
  'yarn', 'yawn', 'year', 'yearn', 'yeast', 'yell', 'yellow', 'yelp', 'yes',
  'yeti', 'yield', 'yodel', 'yoga', 'yogurt', 'yoke', 'yolk', 'young', 'your',
  'youth', 'yummy', 'zany', 'zap', 'zeal', 'zebra', 'zero', 'zest', 'zigzag',
  'zinc', 'zing', 'zip', 'zit', 'zone', 'zoo', 'zoom',
]
